"""patients_id foreign key changed to patient_id

Revision ID: 85f4397f0ee7
Revises: 91d1724e8f3b
Create Date: 2024-05-30 19:44:10.588146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f4397f0ee7'
down_revision = '91d1724e8f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physician_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_appointments_physicians_id_physicians', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_appointments_physician_id_physicians'), 'physicians', ['physician_id'], ['id'])
        batch_op.drop_column('physicians_id')

    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.alter_column('office_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.alter_column('office_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physicians_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_appointments_physician_id_physicians'), type_='foreignkey')
        batch_op.create_foreign_key('fk_appointments_physicians_id_physicians', 'physicians', ['physicians_id'], ['id'])
        batch_op.drop_column('physician_id')

    # ### end Alembic commands ###
